# Generated by Django 2.1.8 on 2019-05-15 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posterUrl', models.TextField(blank=True)),
                ('productionYear', models.IntegerField(default=0)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('runningTime', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('audience', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('channel', models.CharField(max_length=20)),
            ],
        ),
    ]
